apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: redis-pvc
  namespace: monitoring-app

spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
