apiVersion: v1
kind: Service

metadata:
  name: monitoring-stats-service
  namespace: monitoring-app

spec:
  selector:
    app: monitoring-stats

  ports:
    - port: 3002
      targetPort: 3002

  type: ClusterIP
