apiVersion: apps/v1
kind: Deployment

metadata:
  name: monitoring-stats
  namespace: monitoring-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: monitoring-stats

  template:
    metadata:
      labels:
        app: monitoring-stats
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3002"

    spec:
      containers:
        - name: app
          image: monitoring-stats
          imagePullPolicy: Never
          ports:
            - containerPort: 3002

          envFrom:
            - configMapRef:
                name: stats-config

            - secretRef:
                name: stats-secret

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            periodSeconds: 5
            failureThreshold: 3
