apiVersion: v1
kind: Service

metadata:
  name: monitoring-worker-service
  namespace: monitoring-app

spec:
  selector:
    app: monitoring-worker

  ports:
    - port: 3001
      targetPort: 3001

  type: ClusterIP
