apiVersion: apps/v1
kind: Deployment

metadata:
  name: monitoring-worker
  namespace: monitoring-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: monitoring-worker

  template:
    metadata:
      labels:
        app: monitoring-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"

    spec:
      containers:
        - name: app
          image: monitoring-worker
          imagePullPolicy: Never
          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: worker-config

            - secretRef:
                name: worker-secret

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi
