apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: monitoring-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_USER

            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_PASSWORD

            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: /var/lib/grafana/dashboards/monitoring.json

          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards

            - name: dashboards
              mountPath: /var/lib/grafana/dashboards

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 5
            failureThreshold: 3

      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboards
          configMap:
            name: grafana-dashboards
